version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend-prod
    ports:
      - 80:3000
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - 3001:3001
    restart: unless-stopped
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - vidly:/data/db

volumes:
  vidly:
