# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-22T05:54:54Z"
  labels:
    app: Dockerized-Full-Stack-Template-Prod
  name: Dockerized-Full-Stack-Template-Prod
spec:
  containers:
  - args:
    - mongod
    image: docker.io/library/mongo:4.0-xenial
    name: db
    ports:
    - containerPort: 27017
      hostPort: 27017
    volumeMounts:
    - mountPath: /data/configdb
      name: vidlyConfig-pvc
    - mountPath: /data/db
      name: vidly-pvc
  - args:
    - ./docker-entrypoint.sh
    env:
    - name: DB_URL
      value: mongodb://db/vidly
    image: localhost/backend:latest
    name: backend
    ports:
    - containerPort: 3001
      hostPort: 3001
  - args:
    - nginx
    - -g
    - daemon off;
    image: localhost/frontend:1.0.0
    name: frontend-prod
    ports:
    - containerPort: 80
      hostPort: 80
  volumes:
  - name: vidlyConfig-pvc
    persistentVolumeClaim:
      claimName: vidlyConfig
  - name: vidly-pvc
    persistentVolumeClaim:
      claimName: vidly