# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-22T05:54:54Z"
  labels:
    app: Dockerized-Full-Stack-Template-Test
  name: Dockerized-Full-Stack-Template-Test
spec:
  containers:
  - args:
    - mongod
    image: docker.io/library/mongo:4.0-xenial
    name: db
    volumeMounts:
    - mountPath: /data/configdb
      name: vidlyConfig-pvc
    - mountPath: /data/db
      name: vidly-pvc
  - args:
    - npm
    - test
    env:
    - name: DB_URL
      value: mongodb://db/vidly
    image: localhost/backend:latest
    name: backend
  - args:
    - npm
    - test
    image: localhost/frontend:latest
    name: frontend

  volumes:
  - name: vidlyConfig-pvc
    persistentVolumeClaim:
      claimName: vidlyConfig
  - name: vidly-pvc
    persistentVolumeClaim:
      claimName: vidly